export const sampleSongs = [
    {
        artist: "The Weeknd",
        duration: "3:20",
        imageUrl: "https://picsum.photos/200/300",
        name: "Blinding Lights",
        downloadUrl: "https://example.com/song1.mp3",
    },
    {
        artist: "Dua Lipa",
        duration: "3:15",
        imageUrl: "https://picsum.photos/200/300",
        name: "Levitating",
        downloadUrl: "https://example.com/song2.mp3",
    },
    {
        artist: "Bad Bunny",
        duration: "4:05",
        imageUrl: "https://picsum.photos/200/300",
        name: "Dakiti",
        downloadUrl: "https://example.com/song3.mp3",
    },
    {
        artist: "Billie Eilish",
        duration: "3:30",
        imageUrl: "https://picsum.photos/200/300",
        name: "Happier Than Ever",
        downloadUrl: "https://example.com/song4.mp3",
    },
    {
        artist: "Harry Styles",
        duration: "2:54",
        imageUrl: "https://picsum.photos/200/300",
        name: "As It Was",
        downloadUrl: "https://example.com/song5.mp3",
    },
    {
        artist: "Olivia Rodrigo",
        duration: "4:02",
        imageUrl: "https://picsum.photos/200/300",
        name: "drivers license",
        downloadUrl: "https://example.com/song6.mp3",
    },
    {
        artist: "BTS",
        duration: "3:40",
        imageUrl: "https://picsum.photos/200/300",
        name: "Dynamite",
        downloadUrl: "https://example.com/song7.mp3",
    },
    {
        artist: "Taylor Swift",
        duration: "3:39",
        imageUrl: "https://picsum.photos/200/300",
        name: "Anti-Hero",
        downloadUrl: "https://example.com/song8.mp3",
    },
    {
        artist: "Drake",
        duration: "5:12",
        imageUrl: "https://picsum.photos/200/300",
        name: "God's Plan",
        downloadUrl: "https://example.com/song9.mp3",
    },
    {
        artist: "Adele",
        duration: "3:45",
        imageUrl: "https://picsum.photos/200/300",
        name: "Easy On Me",
        downloadUrl: "https://example.com/song10.mp3",
    },
    {
        artist: "Rosalía",
        duration: "2:57",
        imageUrl: "https://picsum.photos/200/300",
        name: "DESPECHÁ",
        downloadUrl: "https://example.com/song11.mp3",
    },
    {
        artist: "Post Malone",
        duration: "3:38",
        imageUrl: "https://picsum.photos/200/300",
        name: "Circles",
        downloadUrl: "https://example.com/song12.mp3",
    },
]

