export const sampleAlbums = [
    {
        artist: "Daft Punk",
        image: "https://picsum.photos/200/300",
        name: "Random Access Memories",
        songs: [
            {
                artist: "Daft Punk & Los Chunguitos",
                duration: "4:34",
                imageUrl: "https://picsum.photos/200/300",
                name: "Give Life Back to Music",
                downloadUrl: "https://example.com/song1.mp3",
            },
            {
                artist: "Daft Punk",
                duration: "5:21",
                imageUrl: "https://picsum.photos/200/300",
                name: "The Game of Love",
                downloadUrl: "https://example.com/song2.mp3",
            },
            {
                artist: "Daft Punk",
                duration: "9:04",
                imageUrl: "https://picsum.photos/200/300",
                name: "Giorgio by Moroder",
                downloadUrl: "https://example.com/song3.mp3",
            },
            {
                artist: "Daft Punk",
                duration: "3:48",
                imageUrl: "https://picsum.photos/200/300",
                name: "Within",
                downloadUrl: "https://example.com/song4.mp3",
            },
            {
                artist: "Daft Punk",
                duration: "5:37",
                imageUrl: "https://picsum.photos/200/300",
                name: "Instant Crush",
                downloadUrl: "https://example.com/song5.mp3",
            },
        ],
    },
    {
        artist: "Kendrick Lamar",
        image: "https://picsum.photos/200/300",
        name: "To Pimp a Butterfly",
        songs: [
            {
                artist: "Kendrick Lamar",
                duration: "4:47",
                imageUrl: "https://picsum.photos/200/300",
                name: "Wesley's Theory",
                downloadUrl: "https://example.com/song6.mp3",
            },
            {
                artist: "Kendrick Lamar & Los Chunguitos",
                duration: "2:10",
                imageUrl: "https://picsum.photos/200/300",
                name: "For Free?",
                downloadUrl: "https://example.com/song7.mp3",
            },
            {
                artist: "Kendrick Lamar",
                duration: "3:54",
                imageUrl: "https://picsum.photos/200/300",
                name: "King Kunta",
                downloadUrl: "https://example.com/song8.mp3",
            },
            {
                artist: "Kendrick Lamar",
                duration: "4:31",
                imageUrl: "https://picsum.photos/200/300",
                name: "Institutionalized",
                downloadUrl: "https://example.com/song9.mp3",
            },
            {
                artist: "Kendrick Lamar",
                duration: "5:00",
                imageUrl: "https://picsum.photos/200/300",
                name: "These Walls",
                downloadUrl: "https://example.com/song10.mp3",
            },
        ],
    },
    {
        artist: "Rosalía",
        image: "https://picsum.photos/200/300",
        name: "El Mal Querer",
        songs: [
            {
                artist: "Rosalía & Los Chunguitos",
                duration: "2:30",
                imageUrl: "https://picsum.photos/200/300",
                name: "Malamente",
                downloadUrl: "https://example.com/song11.mp3",
            },
            {
                artist: "Rosalía",
                duration: "3:15",
                imageUrl: "https://picsum.photos/200/300",
                name: "Que No Salga La Luna",
                downloadUrl: "https://example.com/song12.mp3",
            },
            {
                artist: "Rosalía",
                duration: "3:13",
                imageUrl: "https://picsum.photos/200/300",
                name: "Pienso En Tu Mirá",
                downloadUrl: "https://example.com/song13.mp3",
            },
            {
                artist: "Rosalía",
                duration: "2:39",
                imageUrl: "https://picsum.photos/200/300",
                name: "De Aquí No Sales",
                downloadUrl: "https://example.com/song14.mp3",
            },
            {
                artist: "Rosalía",
                duration: "2:51",
                imageUrl: "https://picsum.photos/200/300",
                name: "Reniego",
                downloadUrl: "https://example.com/song15.mp3",
            },
        ],
    },
]

